# Simple setup for testing.
# Only starts name node and single data node.

version: '2'
services:
    namenode:
      image: analytics/hadoop-namenode
      hostname: namenode
      container_name: namenode
      volumes:
        - ~/datascience-sandbox/hadoop/namenode:/hadoop/dfs/name
        - ~/datascience-sandbox/hadoop/exchange:/exchange
      environment:
        - CLUSTER_NAME=test
      env_file:
        - env/hadoop.env
      ports:
        - "50070:50070"
        - "8020:8020"

    datanode1:
      image: analytics/hadoop-datanode
      hostname: datanode1
      volumes:
        - ~/datascience-sandbox/hadoop/datanode1:/hadoop/dfs/data
      env_file:
        - env/hadoop.env
      depends_on:
        - namenode
